"""Constants for the Jarvis CosyVoice TTS integration."""

DOMAIN = "jarvis_cosyvoice_tts"

CONF_BASE_URL = "base_url"
CONF_BEARER_TOKEN = "bearer_token"
CONF_FALLBACK_ENTITY_ID = "fallback_entity_id"
CONF_REQUEST_TIMEOUT = "request_timeout"
CONF_MULTI_SENTENCE_STREAMING = "multi_sentence_streaming"

DEFAULT_BASE_URL = "http://192.168.1.10:17871"
DEFAULT_FALLBACK_ENTITY_ID = "tts.kokoro"
DEFAULT_REQUEST_TIMEOUT = 300
DEFAULT_MULTI_SENTENCE_STREAMING = False
DEFAULT_LANGUAGE = "en-US"
DEFAULT_VOICE = "default"
DEFAULT_SPEED = 1.2

OPTION_SPEED = "speed"
OPTION_INSTRUCT = "instruct"

STREAM_ENDPOINT = "/synthesize-stream"
STREAM_READ_SIZE = 16 * 1024
MAX_STREAM_MESSAGE_BYTES = 65536
MAX_STREAM_REQUEST_BYTES = 65536
