#!/usr/bin/env python3
"""Upgrade only personality prompts generated by pre-1.6.0 voice profiles."""

from __future__ import annotations

import argparse
import json
import os
import re
import tempfile
from pathlib import Path


OLD_TEMPLATES = (
    (
        "Use light mannerisms associated with {label}, sparingly. Never claim to be that person "
        "or change Jarvis identity, safety, or tool behavior."
    ),
    (
        "Lean fully into the {label} character personality in every conversational response. "
        "Use its recognizable temperament, cadence, vocabulary, mannerisms, worldview, and "
        "occasional signature phrasing so the character is unmistakable, while avoiding repetitive "
        "catchphrases. Do not blend in another assistant persona or describe this as an impression. "
        "Preserve factual accuracy, tool discipline, and safety behavior underneath the character "
        "presentation."
    ),
    (
        "Use conversational mannerisms associated with {label}: its temperament, cadence, vocabulary, "
        "values, and restrained occasional signature phrasing. Let those traits shape the response "
        "naturally while answering the user directly. Never announce, label, or explain the persona, "
        "and never begin with phrases such as 'As {label}'. Do not turn routine answers into speeches, "
        "force catchphrases, or add theatrical grandeur where it does not fit. Do not blend in another "
        "assistant persona. Preserve factual accuracy, tool discipline, and safety behavior."
    ),
    (
        "Use conversational mannerisms associated with {label}: its temperament, cadence, vocabulary, "
        "values, and restrained occasional signature phrasing. Let those traits shape the response "
        "naturally while answering the user directly. Never announce, label, or explain the persona, "
        "and never begin with phrases such as 'As {label}'. Do not turn routine answers into speeches or "
        "add theatrical grandeur where it does not fit. Use recognizable catchphrases sparingly, only when "
        "they fit the conversation naturally. Do not blend in another "
        "assistant persona. Preserve factual accuracy, tool discipline, and safety behavior."
    ),
)
NEW_TEMPLATE = (
    "Use {label} as the sole presentation persona. Use its conversational temperament, cadence, "
    "vocabulary, values, and restrained occasional signature phrasing. Let those traits shape the response "
    "naturally while answering the user directly. Never announce, label, or explain the persona, "
    "and never begin with phrases such as 'As {label}'. Do not turn routine answers into speeches or "
    "add theatrical grandeur where it does not fit. Use recognizable catchphrases sparingly, only when "
    "they fit the conversation naturally. Jarvis remains the operational role and name, not a second "
    "presentation style; do not blend in another assistant or character persona. Preserve factual "
    "accuracy, tool discipline, and safety behavior."
)


def corrected_label(data: dict, current: str) -> str:
    malformed = bool(re.search(r"https?://|(?:youtube\.com|youtu\.be)", current, re.IGNORECASE))
    malformed = malformed or current.casefold().startswith(("uh ", "um "))
    if not malformed:
        return current
    name = " ".join(str(data.get("name") or "the selected voice").split()).strip()
    name = re.sub(r"\s*\([^)]{1,40}\)\s*$", "", name).strip()
    return name or "the selected voice"


def atomic_write(path: Path, data: dict) -> None:
    fd, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            json.dump(data, handle, indent=2, ensure_ascii=True)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
    except Exception:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def migrate(path: Path, apply: bool) -> bool:
    data = json.loads(path.read_text(encoding="utf-8"))
    personality = data.get("personality") or {}
    current_label = str(personality.get("label") or data.get("name") or "the selected voice").strip()
    generated_prompts = {template.format(label=current_label) for template in OLD_TEMPLATES}
    generated_prompts.add(NEW_TEMPLATE.format(label=current_label))
    if personality.get("prompt") not in generated_prompts:
        return False
    label = corrected_label(data, current_label)
    new_prompt = NEW_TEMPLATE.format(label=label)
    changed = (
        label != current_label
        or personality.get("prompt") != new_prompt
        or personality.get("mode") != "character"
        or personality.get("paired_with_voice") is not True
    )
    if not changed:
        return False
    personality.update({"label": label, "mode": "character", "paired_with_voice": True, "prompt": new_prompt})
    data["personality"] = personality
    parts = [str(data.get("delivery_prompt") or "").strip()]
    if personality.get("enabled", True):
        parts.append(new_prompt)
    data["style_prompt"] = " ".join(part for part in parts if part)
    if apply:
        atomic_write(path, data)
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("root", type=Path)
    parser.add_argument("--apply", action="store_true", help="write changes; otherwise report a dry run")
    args = parser.parse_args()
    changed = []
    for area in ("profiles", "candidates"):
        for path in sorted((args.root / area).glob("*/profile.json")):
            if migrate(path, args.apply):
                changed.append(f"{area}/{path.parent.name}")
    print(json.dumps({"applied": args.apply, "count": len(changed), "profiles": changed}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
